import type { Metadata } from 'next';
import './globals.css';
import { Montserrat } from 'next/font/google';

const Font = Montserrat({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Flag Discover',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='pt-br'>
			<body className={`${Font.className}`}>{children}</body>
		</html>
	);
}
